# Generated by Django 5.0.1 on 2024-03-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_author_cni_author_email_author_author_phone_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='lesson_video',
            field=models.FileField(null=True, upload_to='Media/video'),
        ),
    ]
